Changed App Name
GeekHaven/ChatApp pull request #20
Opened 2020-10-17 14:39 UTC by CadencePrestissimo

2020-10-17 18:00 UTC, starboi02 requested changes
@CadencePrestissimo why are there 3 strings with same value TODO?

2020-10-18 07:28 UTC, CadencePrestissimo commented
That happened by mistake , I corrected it

2020-10-18 07:55 UTC, starboi02 approved these changes

2020-10-18 07:55 UTC, merged

2020-10-18 08:10 UTC, starboi02 commented
@CadencePrestissimo this PR has been reverted and would not be counted in the GeekTober as you have already made 6 PRs